pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                script {
					dockerapp = docker.build("izakdvlpr/kubenews:${env.BUILD_ID}", '-f ./web/Dockerfile ./web')
				}
            }
        }
		
		stage('Push Docker Image') {
			steps {
				script {
					docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
						dockerapp.push('latest')
						dockerapp.push("${env.BUILD_ID}")
					}
				}
			}
		}
		
		stage('Deploy Kubernetes') {
			environment {
				tag_version = "${env.BUILD_ID}"
			}
			steps {
				withKubeConfig ([credentialsId: 'kubeconfig']) {
					sh 'seed -i "s/{{TAG}}/$tag_version/g" ./k8s/deployment.yaml'
					sh 'kubectl apply -f ./k8s/deployment.yaml'
				}
			}
		}
    }
}